version: "3.8"
services:
  backend:
    build:
      context: ../backend # Define o diretório de contexto correto
    network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/backend
    environment:
      - FLASK_ENV=development

  
